In [34]:
import numpy as np
item_size = 5  # 待重排物品数
feature_dimension = 3  # 向量维度
max_length = 3

# 精排得分
scores = np.exp(0.01 * np.random.randn(item_size) + 0.2)
print(scores)
# 相似性向量及归一化
feature_vectors = np.random.randn(item_size, feature_dimension)
feature_vectors /= np.linalg.norm(feature_vectors, axis=1, keepdims=True)
# 生成相似度得分矩阵
similarities = np.dot(feature_vectors, feature_vectors.T)

[1.2351593  1.21732296 1.21107065 1.22746389 1.21804903]


In [35]:
similarities

array([[ 1.        , -0.0694668 , -0.22947289,  0.89368868, -0.13800537],
       [-0.0694668 ,  1.        ,  0.96695884,  0.17772823,  0.21770731],
       [-0.22947289,  0.96695884,  1.        ,  0.09844972,  0.04052597],
       [ 0.89368868,  0.17772823,  0.09844972,  1.        , -0.43999586],
       [-0.13800537,  0.21770731,  0.04052597, -0.43999586,  1.        ]])

In [36]:
scores.reshape((1,item_size)).shape

(1, 5)

In [37]:
scores.reshape((1,item_size))*similarities

array([[ 1.2351593 , -0.08456353, -0.27790789,  1.09697059, -0.16809731],
       [-0.08580256,  1.21732296,  1.17105546,  0.21815498,  0.26517818],
       [-0.28343558,  1.17710119,  1.21107065,  0.12084348,  0.04936262],
       [ 1.10384789,  0.21635265,  0.11922957,  1.22746389, -0.53593653],
       [-0.17045862,  0.26502011,  0.04907982, -0.54007903,  1.21804903]])

In [38]:
scores*similarities*scores

array([[ 1.5256185 , -0.10294113, -0.33656608,  1.34649178, -0.20475076],
       [-0.10597983,  1.48187518,  1.4182309 ,  0.26777736,  0.32300003],
       [-0.35008809,  1.4329123 ,  1.46669211,  0.148331  ,  0.06012609],
       [ 1.36342799,  0.26337105,  0.14439543,  1.5066676 , -0.65279697],
       [-0.21054355,  0.32261507,  0.05943912, -0.6629275 ,  1.48364343]])

In [16]:
# 此处是5x1 * 5x5 * 1x5 = 5x5 ，用到了numpy中的广播机制
kernel_matrix = scores.reshape((item_size, 1)) * similarities * scores.reshape((1, item_size))

array([[ 1.47301202,  0.21056307,  0.50341161, -1.10604272, -1.02304781],
       [ 0.21056307,  1.5075574 ,  1.35903587,  0.65631911,  0.63287275],
       [ 0.50341161,  1.35903587,  1.47531538,  0.13261165,  0.58391239],
       [-1.10604272,  0.65631911,  0.13261165,  1.49668171,  0.919277  ],
       [-1.02304781,  0.63287275,  0.58391239,  0.919277  ,  1.47809148]])

In [17]:
kernel_matrix

array([[ 1.47301202,  0.21056307,  0.50341161, -1.10604272, -1.02304781],
       [ 0.21056307,  1.5075574 ,  1.35903587,  0.65631911,  0.63287275],
       [ 0.50341161,  1.35903587,  1.47531538,  0.13261165,  0.58391239],
       [-1.10604272,  0.65631911,  0.13261165,  1.49668171,  0.919277  ],
       [-1.02304781,  0.63287275,  0.58391239,  0.919277  ,  1.47809148]])